apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: wisecow-image:latest
        ports:
        - containerPort: 4499
        command: ["/bin/bash", "-c", "/app/wisecow.sh"]  # Assuming the script is at /app/wisecow.sh
