name: CI/CD for Wisecow Application

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Container Registry
      run:  docker login --username "abinoveramesh" --password "dckr_pat_qh6T7ZjHPLzI5PmbHrVE896F8Bo"


    - name: Build and Push Docker Image
      run: |
        docker build -t abinoveramesh/wisecow-image:latest .
        docker push abinoveramesh/wisecow-image:latest

  deploy-to-kubernetes:
    needs: build-and-push
    runs-on: ubuntu-latest

    env:
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Kubernetes
      run: sudo kubectl apply -f deployment.yaml --validate=false
      env:
        KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }} 
        #$KUBE_CONFIG_DATA
